name: Manual Build and Deploy

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Deployment environment"
        required: true
        default: "development"
  # Push event
  push:
    branches:
      - "main"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: development
    env:
      ENV_NAME: development
    steps:
      - name: Test
        run: |
          env
  build-and-deploy-prod:
    runs-on: ubuntu-latest
    environment:
      name: production
    env:
      ENV_NAME: production
    steps:
      - name: Test
        run: |
          env
