# This is a reusable workflow defined in .github/workflows/deploy.yml
name: Reusable Deployment Workflow

on:
  workflow_call:
    inputs:
      environment_name:
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Deploy
        run: echo "Deploying to ${{ inputs.environment_name }}"
