name: Manual Build and Deploy

# on:
#   workflow_dispatch:
#     inputs:
#       environment:
#         description: "Deployment environment"
#         required: true
#         default: "development"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: development
    steps:
      - name: Test
        run: |
          env
