# This is a calling workflow defined in another .github/workflows file
name: Call Reusable Workflow

on:
  push:
    branches:
      - main
      - develop

jobs:
  call-deploy-workflow:
    uses: ./deploy.yml
    with:
      environment_name: ${{ github.ref == 'refs/heads/main' && 'production' || 'development' }}
