# This is a calling workflow defined in another .github/workflows file
name: Call Reusable Workflow

on:
  push: null

jobs:
  call-deploy-workflow:
    uses: ./.github/workflows/deploy.yml
    with:
      environment_name: ${{ github.ref == 'refs/heads/main' && 'production' || 'development' }}
